Arm 7.17.5
jfrog/JFrog-Cloud-Installers pull request #104
Opened 2021-04-29 15:36 UTC by anupteal

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

<!--
Thank you for contributing . 

Latest changes has committed for Artifactory version 7.17.5 & X-ray version 3.22.1 in all required files.
@danielmkn , Please verify and merge it.

2021-04-29 21:06 UTC, danielmkn requested changes

2021-04-29 21:06 UTC, danielmkn commented on AzureResourceManager/Artifactory/azuredeploy.json
> +      "offer": "artifactory-vm-preview",
Please remove "-preview"

2021-04-29 21:06 UTC, danielmkn commented on AzureResourceManager/Artifactory/azuredeploy.json
> +        "product": "artifactory-vm-preview"
Please remove "-preview"

2021-04-29 21:06 UTC, danielmkn commented on AzureResourceManager/Artifactory/azuredeploy.json
> +        "product": "artifactory-vm-preview"
Please remove "-preview"

2021-04-30 13:53 UTC, anupteal commented
-preview removed from all three places. Please review it again and merge it.

2021-04-30 17:42 UTC, danielmkn approved these changes

2021-04-30 17:42 UTC, merged