PTRENG-3570_Azure setprivateip
jfrog/JFrog-Cloud-Installers pull request #198
Opened 2022-01-31 15:34 UTC by Logeshwarsn

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2022-02-01 00:20 UTC, danielmkn requested changes

2022-02-01 07:11 UTC, Logeshwarsn commented on AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json
> +              "required": true,
Field was removed

2022-02-01 07:12 UTC, Logeshwarsn commented on AzureResourceManager/Artifactory/MP_submission/createUiDefinition.json
> +              "regex": "^[a-z0-9A-Z]{1,30}$",
sure, I have removed those verification coz this field wont required

2022-03-09 01:43 UTC, danielmkn commented
There are no changes in the `azuredeploy.parameters.json`. This file should provide the identical set of parameters with `createUiDefinition.json`

2022-03-09 03:02 UTC, danielmkn commented
`azuredeploy.json` has a problem, see the error below. I've tested the template from the master branch with the same parameters and the deployment was successful.
Artifactory UI is not starting btw, so looks like we have another problem to solve as well.   

`{'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'azuredeploy' is not valid according to the validation procedure. The tracking id is 'b09b9220-f079-46c9-beb3-2157a4c7f480'. See inner errors for details."}

Inner Errors:
{'code': 'InvalidResourceReference', 'message': 'Resource /subscriptions/<subscription_id>/resourceGroups/daniel-artifactory-test/providers/Microsoft.Network/loadBalancers/rthaos3qxlb/frontendIPConfigurations/rthaos3qxlbprimaryFepoolprimaryIpConfig referenced by resource /subscriptions/<subscription_id>/resourceGroups/daniel-artifactory-test/providers/Microsoft.Network/loadBalancers/rthaos3qxlb/loadBalancingRules/HTTPRulePrimary was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.'}`

Also, UI definition wasn't accepting master and join keys generated with `openssl rand -hex 32`, which is the recommended way. I've fixed that and committed.

2022-06-15 17:40 UTC, danielmkn submitted a review, later dismissed

2022-06-15 17:52 UTC, closed without merging