[ansible/artifactory] Conditionally start Artifactory service
jfrog/JFrog-Cloud-Installers pull request #260
Opened 2023-02-15 15:54 UTC by vlinevych

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
In my use case I build an AMI image of artifactory host. 
The role starts Artifactory service unconditionally,  which is harmful in my case, because
Artifactory process connects to existing database and may perform an unwanted database migration.

This PR adds a variable `artifactory_start_service` that defaults to true.
When set to false, it prevents handlers from starting Artifactory and skips the health check at the end.

2023-02-20 04:18 UTC, Logeshwarsn commented
@vlinevych Thanks for the PR, we will include this changes in our next jfrog-platform minor release.

2023-02-22 02:30 UTC, chukka commented
@vlinevych Thanks for PR ! Also, Can you please do changes in upgrade flow (tasks/upgrade.yml) in same PR ?

2023-02-22 02:31 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml
> +  when:
please add same change in upgrade.yaml

2023-02-22 02:32 UTC, chukka requested changes

2023-02-22 02:32 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml
> -  when: not ansible_check_mode
please add same change in upgrade.yaml

2023-03-04 19:16 UTC, chukka commented
@vlinevych I did required changes , so you can ignore

2023-03-04 19:16 UTC, merged