[ansible/artifactory, ansible/xray] Allow using crontab
jfrog/JFrog-Cloud-Installers pull request #276
Opened 2023-03-24 09:00 UTC by vlinevych

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Artifactory and Xray rely on crontab to facilitate log rotation.
Current ansible roles do not configure access to crontab for users `artifactory` or `xray`. 
This results in the following errors:

```
xrayManage.sh[43290]: /etc/cron.allow: Permission denied
```

and

```
The user artifactory cannot use this program (crontab)
The user xray cannot use this program (crontab)
```

I haven't checked other products for this problem, please let me know if the fix needs to be added to other roles.

2023-03-24 09:52 UTC, chukka commented
@vlinevych Thanks for the PR ! I would like this to be optional (default false with variable to switch true/false ) . You seems have added in install flow only ,Please add in upgrade flow as well so that existing users can use this feature.

Also, please add this to all other roles(insight,distribution)  as well in same PR :)

2023-03-27 14:39 UTC, chukka requested changes
You seems have added in install flow only ,Please add in upgrade flow as well so that existing users can use this feature.

2023-03-28 10:29 UTC, vlinevych commented
> @vlinevych Thanks for the PR ! I would like this to be optional (default false with variable to switch true/false ) . You seems have added in install flow only ,Please add in upgrade flow as well so that existing users can use this feature.
> 
> Also, please add this to all other roles(insight,distribution) as well in same PR :)

Thank you for the feedback, the requested changes are done.

2023-03-28 11:06 UTC, chukka commented
@vlinevych Thanks for the update, you may need to wait for next patch , which will happen next week , we already cut the branch for 10.12.1 release (will happen today)

2023-03-28 11:27 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml
> +  file:
@vlinevych pls add `ansible.builtin.file` instead of file

2023-03-28 11:28 UTC, chukka requested changes

2023-03-28 11:28 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml
> +  file:
@vlinevych pls add `ansible.builtin.file` instead of file

2023-03-28 11:28 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/install.yml
> +  file:
@vlinevych pls add `ansible.builtin.file` instead of file

2023-03-28 11:28 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/distribution/tasks/upgrade.yml
> +  file:
@vlinevych pls add `ansible.builtin.file` instead of file

2023-03-28 11:28 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/insight/tasks/install.yml
> +  file:
@vlinevych pls add `ansible.builtin.file` instead of file

2023-03-28 11:28 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/insight/tasks/upgrade.yml
> +  file:
@vlinevych pls add `ansible.builtin.file` instead of file

2023-03-28 11:28 UTC, chukka commented on Ansible/ansible_collections/jfrog/platform/roles/xray/tasks/install.yml
> +  file:
@vlinevych pls add `ansible.builtin.file` instead of file

2023-04-04 11:24 UTC, chukka approved these changes
LGTM, will be part of next  minor release (ETA , 2~3 weeks)

2023-05-03 15:01 UTC, merged