[ansible/artifactory] Updating flag handler to be boolean
jfrog/JFrog-Cloud-Installers pull request #285
Opened 2023-04-17 16:53 UTC by MadOtis

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Title of the PR starts with installer/product name (e.g. `[ansible/artifactory]`)
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md

**What this PR does / why we need it**:
Found a recent MR in the master branch that wasn't working as expected.  The addition of the 'artifactory_start_service` seemed to be not working as expected when trying to use it to build an AWS AMI image, where the service should not start.  Instead, the Ansible portion was failing because the playbook/role was still trying to start the Artifactory image when artifactory_start_service was defined as 'false'.  Adding the `| bool` to the playbook allowed it to skip the startup and subsequent restart of the Arifactory service when passed in an AMI creation task.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #284

**Special notes for your reviewer**:
@alexhung @hexa2k9 @yoav @freddy33 @diginc

2023-04-19 15:08 UTC, MadOtis commented
I have read the CLA Document and I hereby sign the CLA

2023-04-20 10:26 UTC, bbaassssiiee requested changes
Please remove the trailing spaces

2023-04-20 10:26 UTC, bbaassssiiee commented on Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/install.yml
> +    - artifactory_start_service
trailing space

2023-04-20 10:26 UTC, bbaassssiiee commented on Ansible/ansible_collections/jfrog/platform/roles/artifactory/tasks/upgrade.yml
> +    - artifactory_start_service
trailing space

2023-04-21 00:00 UTC, closed without merging